### ISSUE TITLE
Shokofin unexpected interal server error

### ISSUE THREAD

**Issue by johanno** [ShokoAnime/Shokofin#60] opened 2024-07-07 19:07 UTC
### Jellyfin version.

10.9.7

### Shokofin version.

4.0.1.0

### Shoko Server version, release channel, and commit hash.

4.2.2.0, https://truecharts.org/charts/stable/shoko-server/

### File structure of your _Media Library Folder in Jellyfin_/_Import Folder in Shoko Server_.

Anime/Episode1.mkv, Anime/Episode2.mkv, Anime/Season1/Episode1.mkv ....
Basically there is no  structure.

### Screenshot of the "library settings" section of the plugin settings.

![shokofin_1](https://github.com/ShokoAnime/Shokofin/assets/3743347/34480668-7296-4a83-b897-bebcba023ddf)
![shokofin_2](https://github.com/ShokoAnime/Shokofin/assets/3743347/14d70f71-bb42-47c6-8c70-bae564118627)
![shokofin_3](https://github.com/ShokoAnime/Shokofin/assets/3743347/3ea2c74f-e7d3-4851-b745-b312f0e7fd97)
![shokofin_4](https://github.com/ShokoAnime/Shokofin/assets/3743347/4c560376-61c6-4549-951e-8b20d02dc69a)

### Library Type(s).

Shows

### Do the issue persists after creating a library with Shoko set as the only metadata provider? (Now is your time to check if you haven't already.)

- [X] Yes, I hereby confirm that the issue persists after creating a library with Shoko set as the only metadata provider.

### Issue

Refresh metadata crashes the plugin like shown in the stack trace.

### Stack Trace

```
2024-07-07 21:06:16.201244+02:00[21:06:16] [WRN] [58] Shokofin.Providers.SeriesProvider: Unable to find show info for path /media/Animes/[Erai-raws] Ookami to Koushinryou - 01 ~ 13 [480p][Multiple Subtitle]
2024-07-07 21:06:16.259014+02:00[21:06:16] [ERR] [38] Shokofin.Resolvers.ShokoResolver: Threw unexpectedly; InternalServerErrorException
2024-07-07 21:06:16.259035+02:00Shokofin.API.Models.ApiException: InternalServerErrorException
2024-07-07 21:06:16.259043+02:00at Shokofin.API.ShokoAPIClient.Get[ReturnType](String url, HttpMethod method, String apiKey, Boolean skipCache)
2024-07-07 21:06:16.259050+02:00at Shokofin.API.ShokoAPIClient.GetFilesForImportFolder(Int32 importFolderId, String subPath, Int32 page)
2024-07-07 21:06:16.259063+02:00at Shokofin.Resolvers.VirtualFileSystemService.GetFilesForImportFolder(IReadOnlyList`1 mediaConfigs, HashSet`1 fileSet)+MoveNext()
2024-07-07 21:06:16.259071+02:00at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
2024-07-07 21:06:16.259077+02:00at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)
2024-07-07 21:06:16.259083+02:00at Shokofin.Resolvers.VirtualFileSystemService.GenerateStructure(Nullable`1 collectionType, String vfsPath, IEnumerable`1 allFiles)
2024-07-07 21:06:16.259089+02:00at Shokofin.Resolvers.VirtualFileSystemService.<>c__DisplayClass16_0.<<GenerateStructureInVFS>b__2>d.MoveNext()
2024-07-07 21:06:16.259095+02:00--- End of stack trace from previous location ---
2024-07-07 21:06:16.259100+02:00at Shokofin.Utils.GuardedMemoryCache.GetOrCreateAsync[TItem](Object key, Func`1 createFactory, MemoryCacheEntryOptions createOptions)
2024-07-07 21:06:16.259106+02:00at Shokofin.Resolvers.VirtualFileSystemService.GenerateStructureInVFS(Folder mediaFolder, String path)
2024-07-07 21:06:16.259112+02:00at Shokofin.Resolvers.ShokoResolver.ResolveMultiple(Folder parent, Nullable`1 collectionType, List`1 fileInfoList)
2024-07-07 21:06:16.259276+02:00[21:06:16] [ERR] [38] MediaBrowser.Controller.Entities.BaseItem: Error retrieving children
2024-07-07 21:06:16.259302+02:00Shokofin.API.Models.ApiException: InternalServerErrorException
2024-07-07 21:06:16.259313+02:00at Shokofin.API.ShokoAPIClient.Get[ReturnType](String url, HttpMethod method, String apiKey, Boolean skipCache)
2024-07-07 21:06:16.259324+02:00at Shokofin.API.ShokoAPIClient.GetFilesForImportFolder(Int32 importFolderId, String subPath, Int32 page)
2024-07-07 21:06:16.259335+02:00at Shokofin.Resolvers.VirtualFileSystemService.GetFilesForImportFolder(IReadOnlyList`1 mediaConfigs, HashSet`1 fileSet)+MoveNext()
2024-07-07 21:06:16.259346+02:00at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
2024-07-07 21:06:16.259356+02:00at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)
2024-07-07 21:06:16.259365+02:00at Shokofin.Resolvers.VirtualFileSystemService.GenerateStructure(Nullable`1 collectionType, String vfsPath, IEnumerable`1 allFiles)
2024-07-07 21:06:16.259374+02:00at Shokofin.Resolvers.VirtualFileSystemService.<>c__DisplayClass16_0.<<GenerateStructureInVFS>b__2>d.MoveNext()
2024-07-07 21:06:16.259383+02:00--- End of stack trace from previous location ---
2024-07-07 21:06:16.259392+02:00at Shokofin.Utils.GuardedMemoryCache.GetOrCreateAsync[TItem](Object key, Func`1 createFactory, MemoryCacheEntryOptions createOptions)
2024-07-07 21:06:16.259403+02:00at Shokofin.Resolvers.VirtualFileSystemService.GenerateStructureInVFS(Folder mediaFolder, String path)
2024-07-07 21:06:16.259414+02:00at Shokofin.Resolvers.ShokoResolver.ResolveMultiple(Folder parent, Nullable`1 collectionType, List`1 fileInfoList)
2024-07-07 21:06:16.259424+02:00at Shokofin.Resolvers.ShokoResolver.MediaBrowser.Controller.Resolvers.IMultiItemResolver.ResolveMultiple(Folder parent, List`1 files, Nullable`1 collectionType, IDirectoryService directoryService)
2024-07-07 21:06:16.259434+02:00at Emby.Server.Implementations.Library.LibraryManager.ResolvePaths(IEnumerable`1 files, IDirectoryService directoryService, Folder parent, LibraryOptions libraryOptions, Nullable`1 collectionType, IItemResolver[] resolvers)
2024-07-07 21:06:16.259443+02:00at MediaBrowser.Controller.Entities.Folder.GetNonCachedChildren(IDirectoryService directoryService)
2024-07-07 21:06:16.259466+02:00at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
2024-07-07 21:06:21.227850+02:00[21:06:21] [INF] [38] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Started library sync
2024-07-07 21:06:21.297378+02:00[21:06:21] [INF] [38] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Library Sync: Updated 1 items
```

**Comment by johanno** [comment] 2024-07-07 19:10
Maybe I have setup sth. wrong. I do not fully understand how shoko works, or this plugin, but I assumed that it should just work.

Also thanks for updating to 10.9. Truenas downgrading wasn't possible for me.

**Comment by revam** [comment] 2024-07-08 22:27
Actually a duplicate of #61 (which I just transferred back to this repository for people to find when searching for their issue). So run the task to clean up missing file locations in Shoko Server and you should be good to go. @johanno @sigmakey 

I'm closing both issues now.

**Comment by revam** [comment] 2024-07-08 22:38
Posting the screenshot here too, in case people discover this issue first and don't bother going to the other issue.

![image](https://github.com/ShokoAnime/Shokofin/assets/7761729/0eac752b-de25-43b9-93cd-574bf00f5e3e)

**Comment by revam** [comment] 2024-07-08 22:52
Feel free to reopen this issue if running the action (and making sure it completes) followed by a new scan/refresh doesn't fix the issue.

**Comment by johanno** [comment] 2024-07-09 21:52
I only have the option "Remove Missing Files" and it did not work.

`2024-07-09 00:33:40
Connection id "0HN4M41ELL33P", Request id "0HN4M41ELL33P:00000003": An unhandled exception was thrown by the application.
2024-07-08T22:34:46.9085027Z
Event '00000000000000000000000000000000' queued.
2024-07-08T22:34:46.9085027Z
Connection id "0HN4M41ELL33P", Request id "0HN4M41ELL33P:00000004": An unhandled exception was thrown by the application.
2024-07-08T22:36:03.7364283Z
Remove Missing Files: Start
2024-07-08T22:36:03.8015704Z
Remove Missing Files: Finished
2024-07-08T22:37:58.9913388Z
Event '00000000000000000000000000000000' queued.
2024-07-08T22:37:58.9913388Z
Connection id "0HN4M41ELL36C", Request id "0HN4M41ELL36C:00000002": An unhandled exception was thrown by the application.`

**Comment by johanno** [comment] 2024-07-09 21:53
I can not open the issue again.

**Comment by revam** [comment] 2024-07-10 00:35
for now, I'll recommend subscribing to #61, and/or add future comments in that issue if you have something to add. and I'll leave both issues open until a fix have been found (for stable shoko server users, as the issue has already been patched in daily shoko server).

**Comment by revam** [comment] 2024-07-12 13:48
See https://github.com/ShokoAnime/Shokofin/issues/61#issuecomment-2220744297 fir hiw to fix it.

**Closed by revam** 2024-07-12 13:48 UTC
Labels: Duplicate
